name: 'clan_analytics'
version: '1.0'
config-version: 2

profile: 'clan_analytics'

model-paths: ['models']
clean-targets: ['target', 'dbt_packages']

models:
  clan_analytics:
    +materialized: table
    staging:
      +materialized: view
